services:
  nastools:
    image: nastools/nas-tools:latest
    container_name: nastools
    ports:
      - 3000:3000 
    volumes:
      - /volume1/My/Docker/nastools:/config
      - /volume1/My/Video:/downloads
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
      - UMASK=022
    restart: always
    network_mode: bridge
