services:
  qinglong: # 服务名称
    image: whyour/qinglong:latest # 镜像名称（可更改冒号后版本）
    container_name: qinglong # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 11010:5700
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/My/Docker/qinglong:/ql/data
    environment:
      - QlPort=5700
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
