services:
  qbittorrent: # 服务名称
    image: linuxserver/qbittorrent:4.6.6 # 镜像名称（可更改冒号后版本）
    container_name: qbittorrent # 容器名称（可更改）
    privileged: true # 配置最高权限
    ports: # 容器端口（可更改冒号前端口）
      - 3020:3020
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /volume1/@home/Testroot/Docker/qbittorrent:/config
      - /volume1/@home/Testroot/Video:/downloads
    environment: # 环境变量
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=3020
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
