services:

  db:
    image: mariadb
    container_name: mysql
    privileged: true
    volumes:
      - /vol1/1000/Docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=teamspeak
    restart: always
  
  teamspeak:
    image: teamspeak
    container_name: teamspeak
    privileged: true
    user: 1001:100
    ports:
      - 10010:9987/udp
      - 30033:30033
      - 41144:41144
      - 10011:10011
    volumes:
      - /volume1/@home/Testroot/Docker/teamspeak:/var/ts3server
      - /volume1/@home/Testroot/Docker/teamspeak/files:/var/ts3server/files
      - /volume1/@home/Testroot/Docker/teamspeak/logs:/var/ts3server/logs
    environment:
      - TS3SERVER_DB_PLUGIN=ts3db_mariadb
      - TS3SERVER_DB_SQLCREATEPATH=create_mariadb
      - TS3SERVER_DB_HOST=db
      - TS3SERVER_DB_USER=root
      - TS3SERVER_DB_PASSWORD=password
      - TS3SERVER_DB_NAME=teamspeak
      - TS3SERVER_DB_WAITUNTILREADY=30
      - TS3SERVER_LICENSE=accept
    restart: always
