services:
  clouddriver2:
    image: cloudnas/clouddrive2:latest
    container_name: clouddriver2
    ports:
      - 12000:19798
    volumes:
      - /vol1/1000/Docker/clouddrive2:/Config
    environment:
      - TZ=Asia/Shanghai
      - CLOUDDRIVE_HOME=/Config
    restart: always
    network_mode: bridge
