services:
  firefox: # 服务名称
    image: jlesage/firefox:latest # 镜像名称（可更改冒号后版本）
    container_name: firefox # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 8010:5800
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/firefox/config:/config:rw
      - /vol1/1000/Docker/firefox/fonts:/usr/share/fonts
      - /vol1/1000/Downloads:/config/downloads
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
