services:
  icloudpd:
    image: docker.ifuck.me/icloudpd/icloudpd:latest
    container_name: icloudpd
    tty: true
    ports:
      - 8080:8080
    volumes:
      - /vol1/1000/Photos:/data
    environment:
      - TZ=Asia/Shanghai
    command: icloudpd --directory /data --username 1563119813@qq.com --mfa-provider webui --domain cn --password-provider webui --watch-with-interval 3600
    restart: always
    network_mode: bridge
