services:
  iyuuplus: # 服务名称
    image: iyuucn/iyuuplus:latest # 镜像名称（可更改冒号后版本）
    container_name: iyuuplus # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 3030:8780
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/iyuuplus/iyuu:/iyuu
      - /vol1/1000/Docker/iyuuplus/data:/data
  #    需要安装 qbittorrent 和 transmission 下载器
  #    - /vol1/1000/Docker/qbittorrent/qBittorrent/BT_backup:/qb
  #    - /vol1/1000/Docker/transmission/torrents:/tr
    environment: # 环境变量
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
