services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 11030:5432
    volumes:
      - /vol1/1000/Docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=meiyutao
      - POSTGRES_PASSWORD=Yt20010322.
      - POSTGRES_DB=mydb
      
