services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest # 镜像名称（可更改冒号后版本）
    container_name: pdftool # 容器名称（可更改）
    ports: # 容器端口（可更改冒号前端口）
      - 7020:8080
    volumes: # 冒号前替换成自身路径即可（可更改）
      - /vol1/1000/Docker/pdftool/trainingData:/usr/share/tessdata
      - /vol1/1000/Docker/pdftool/extraConfigs:/configs
      - /vol1/1000/Docker/pdftool/customFiles:/customFiles/
      - /vol1/1000/Docker/pdftool/logs:/logs/
      - /vol1/1000/Docker/pdftool/pipeline:/pipeline/
    environment: # 环境变量
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
    restart: always # 总是启动容器
    network_mode: bridge # 网络桥接
