services:

  db:
    image: mariadb
    container_name: mysql
    volumes:
      - /vol1/1000/Docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: teamspeak
    restart: always
  
  teamspeak:
    image: teamspeak
    container_name: teamspeak
    ports:
      - 10020:9987/udp
      - 30033:30033
      - 41144:41144
      - 10011:10011
    volumes:
      - /vol1/1000/Docker/teamspeak:/var/ts3server
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: password
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    restart: always
